/*
 * main.c — Camera filter + compress demo host application
 *
 * Two-module event-driven pipeline:
 *
 *   frame_filter   — wakes on CAMERA_FRAME_READY (event 0).  Computes MAD of the
 *                    camera frame; accepts high-variance frames and posts
 *                    DATA_CAPTURED (event 1); rejects low-variance frames.
 *
 *   frame_compress — wakes on DATA_CAPTURED (event 1).  Re-reads the camera frame
 *                    and applies RLE compression, logging the stats.
 *
 * The host drives the pipeline by calling fuse_post_event(CAMERA_FRAME_READY) once
 * per simulated frame, then polling fuse_tick() until both modules have been
 * triggered (or the frame is rejected by the filter).
 *
 * Usage (static policy mode only):
 *   camera_filter_compress_host <frame_filter.aot> <frame_compress.aot>
 *
 *   Policy is read from FUSE_POLICY_FRAME_FILTER_* and FUSE_POLICY_FRAME_COMPRESS_*
 *   macros compiled in from fuse_app_config.h.  Rebuild with
 *   -DFUSE_APP_CONFIG=<path/to/app_config.json> to generate the header.
 */

#include <assert.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#include "fuse.h"

/* ---------------------------------------------------------------------------
 * Compile-time app config (generated by tools/gen_app_config.py).
 * Present only when CMake is invoked with -DFUSE_APP_CONFIG=app_config.json.
 * --------------------------------------------------------------------------- */
#if defined(__has_include) && __has_include("fuse_app_config.h")
#  include "fuse_app_config.h"
#endif

/* Fail loudly if static policy macros are unavailable — this demo requires them. */
#ifndef FUSE_POLICY_FRAME_FILTER_CAPABILITIES
#  error "fuse_app_config.h not found or macros missing.  " \
         "Rebuild with: cmake -DFUSE_APP_CONFIG=<path/to/app_config.json> ..."
#endif

/* ---------------------------------------------------------------------------
 * Static FUSE memory pools (no dynamic allocation for FUSE itself).
 * Sizes come from app_config.h macros.
 * --------------------------------------------------------------------------- */
static uint8_t g_module_mem[FUSE_APP_WAMR_POOL_BYTES];
static uint8_t g_log_mem[FUSE_APP_LOG_POOL_BYTES];

/* ---------------------------------------------------------------------------
 * Simulated camera
 * --------------------------------------------------------------------------- */
#define SIM_FRAME_SIZE  (256u * 1024u)   /* 256 KB synthetic frame */

static uint8_t g_sim_frame[SIM_FRAME_SIZE];

/*
 * init_sim_frame — populate g_sim_frame with a test pattern.
 *
 * varied=1  → cycling pattern i & 0xFF — MAD ≈ 85, passes the filter.
 * varied=0  → uniform 0x80              — MAD  = 0, rejected by the filter.
 */
static void init_sim_frame(int varied)
{
    uint32_t i;
    if (varied) {
        for (i = 0u; i < SIM_FRAME_SIZE; ++i) {
            g_sim_frame[i] = (uint8_t)(i & 0xFFu);
        }
    } else {
        for (i = 0u; i < SIM_FRAME_SIZE; ++i) {
            g_sim_frame[i] = 0x80u;
        }
    }
}

/* ---------------------------------------------------------------------------
 * HAL callbacks
 * --------------------------------------------------------------------------- */

static uint64_t hal_timer(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000u + (uint64_t)(ts.tv_nsec / 1000u);
}

static uint64_t hal_camera(void *buf, uint32_t max_len)
{
    /* buf has already been validated by fuse_native_camera_last_frame()
     * via wasm_runtime_validate_native_addr() before this callback is
     * invoked (see core/camera/fuse_hal_camera.c).  A NULL check here is a
     * defence-in-depth guard only. */
    if (buf == NULL || max_len == 0u) {
        return 0u;
    }
    uint32_t copy_len = (SIM_FRAME_SIZE < max_len) ? SIM_FRAME_SIZE : max_len;
    memcpy(buf, g_sim_frame, copy_len);
    return (uint64_t)copy_len;
}

/* Quota timer uses SIGALRM + setitimer.  The signal handler may only call
 * async-signal-safe functions; fuse_quota_expired() only calls
 * wasm_runtime_terminate() and an atomic fence, which is ISR-safe. */
static volatile sig_atomic_t g_quota_module_id = -1;

static void sigalrm_handler(int sig)
{
    (void)sig;
    if (g_quota_module_id >= 0) {
        fuse_quota_expired((fuse_module_id_t)(unsigned int)g_quota_module_id);
    }
}

static void hal_quota_arm(fuse_module_id_t mid, uint32_t quota_us)
{
    /* Write the module ID before arming the timer.  The compiler/CPU fence
     * ensures this store is visible before the setitimer syscall that may
     * cause SIGALRM to fire on a weakly-ordered architecture. */
    g_quota_module_id = (sig_atomic_t)mid;
    __atomic_thread_fence(__ATOMIC_SEQ_CST);

    struct itimerval itv;
    memset(&itv, 0, sizeof(itv));
    itv.it_value.tv_sec  = (time_t)(quota_us / 1000000u);
    itv.it_value.tv_usec = (suseconds_t)(quota_us % 1000000u);
    setitimer(ITIMER_REAL, &itv, NULL);
}

static void hal_quota_cancel(fuse_module_id_t mid)
{
    (void)mid;

    /* Disarm the timer first. */
    struct itimerval zero;
    memset(&zero, 0, sizeof(zero));
    setitimer(ITIMER_REAL, &zero, NULL);

    /* Block SIGALRM while clearing the module ID to close the window where
     * the signal could fire after disarm but before the ID is reset,
     * spuriously calling fuse_quota_expired() on the next step's module. */
    sigset_t mask, old_mask;
    sigemptyset(&mask);
    sigaddset(&mask, SIGALRM);
    sigprocmask(SIG_BLOCK, &mask, &old_mask);
    g_quota_module_id = -1;
    sigprocmask(SIG_SETMASK, &old_mask, NULL);
}

/* ---------------------------------------------------------------------------
 * Helpers
 * --------------------------------------------------------------------------- */

static uint8_t *read_file(const char *path, uint32_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "error: cannot open '%s'\n", path);
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    rewind(f);
    if (sz <= 0) {
        fprintf(stderr, "error: empty or unreadable file '%s'\n", path);
        fclose(f);
        return NULL;
    }
    if ((unsigned long)sz > (unsigned long)UINT32_MAX) {
        fprintf(stderr, "error: file '%s' exceeds 4 GB\n", path);
        fclose(f);
        return NULL;
    }
    uint8_t *buf = (uint8_t *)malloc((size_t)sz);
    if (!buf) {
        fprintf(stderr, "error: malloc failed for %ld bytes\n", sz);
        fclose(f);
        return NULL;
    }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        fprintf(stderr, "error: short read on '%s'\n", path);
        free(buf);
        fclose(f);
        return NULL;
    }
    fclose(f);
    *out_size = (uint32_t)sz;
    return buf;
}

static const char *fuse_stat_name(fuse_stat_t s)
{
    switch (s) {
        case FUSE_SUCCESS:               return "FUSE_SUCCESS";
        case FUSE_ERR_QUOTA_EXCEEDED:    return "FUSE_ERR_QUOTA_EXCEEDED";
        case FUSE_ERR_MODULE_TRAP:       return "FUSE_ERR_MODULE_TRAP";
        case FUSE_ERR_INVALID_ARG:       return "FUSE_ERR_INVALID_ARG";
        case FUSE_ERR_NOT_INITIALIZED:   return "FUSE_ERR_NOT_INITIALIZED";
        case FUSE_ERR_MODULE_NOT_FOUND:  return "FUSE_ERR_MODULE_NOT_FOUND";
        default:                          return "FUSE_ERR_OTHER";
    }
}

/* Returns 1 if module state is terminal (TRAPPED or QUOTA_EXCEEDED). */
static int module_is_terminal(fuse_module_id_t id)
{
    fuse_module_state_t st;
    if (fuse_module_stat(id, &st) != FUSE_SUCCESS) {
        return 1;
    }
    return (st == FUSE_MODULE_STATE_TRAPPED ||
            st == FUSE_MODULE_STATE_QUOTA_EXCEEDED);
}

/* ---------------------------------------------------------------------------
 * main
 * --------------------------------------------------------------------------- */

#define NUM_FRAMES          8
#define MAX_TICKS_PER_FRAME 100

int main(int argc, char *argv[])
{
    if (argc != 3) {
        fprintf(stderr,
                "usage: %s <frame_filter.aot> <frame_compress.aot>\n"
                "\n"
                "  Requires fuse_app_config.h compiled in via:\n"
                "    cmake -DFUSE_APP_CONFIG=<path/to/app_config.json> ...\n",
                argv[0]);
        return 1;
    }

    /* --- Register SIGALRM handler for CPU quota --- */
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = sigalrm_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;  /* no SA_RESTART: wasm call should be interrupted */
    if (sigaction(SIGALRM, &sa, NULL) != 0) {
        perror("sigaction");
        return 1;
    }

    /* --- Load AOT binaries --- */
    uint32_t filter_size = 0u;
    uint8_t *filter_buf  = read_file(argv[1], &filter_size);
    if (!filter_buf) return 1;

    uint32_t compress_size = 0u;
    uint8_t *compress_buf  = read_file(argv[2], &compress_size);
    if (!compress_buf) {
        free(filter_buf);
        return 1;
    }

    /* --- Build policies from compiled-in macros --- */
    fuse_policy_t filter_policy;
    filter_policy.capabilities     = FUSE_POLICY_FRAME_FILTER_CAPABILITIES;
    filter_policy.memory_pages_max = FUSE_POLICY_FRAME_FILTER_MEMORY_PAGES_MAX;
    filter_policy.stack_size       = FUSE_POLICY_FRAME_FILTER_STACK_SIZE;
    filter_policy.heap_size        = FUSE_POLICY_FRAME_FILTER_HEAP_SIZE;
    filter_policy.cpu_quota_us     = FUSE_POLICY_FRAME_FILTER_CPU_QUOTA_US;
    filter_policy.step_interval_us = FUSE_POLICY_FRAME_FILTER_STEP_INTERVAL_US;
    filter_policy.activation_mask  = FUSE_POLICY_FRAME_FILTER_ACTIVATION_MASK;
    filter_policy.event_subscribe  = FUSE_POLICY_FRAME_FILTER_EVENT_SUBSCRIBE;

    fuse_policy_t compress_policy;
    compress_policy.capabilities     = FUSE_POLICY_FRAME_COMPRESS_CAPABILITIES;
    compress_policy.memory_pages_max = FUSE_POLICY_FRAME_COMPRESS_MEMORY_PAGES_MAX;
    compress_policy.stack_size       = FUSE_POLICY_FRAME_COMPRESS_STACK_SIZE;
    compress_policy.heap_size        = FUSE_POLICY_FRAME_COMPRESS_HEAP_SIZE;
    compress_policy.cpu_quota_us     = FUSE_POLICY_FRAME_COMPRESS_CPU_QUOTA_US;
    compress_policy.step_interval_us = FUSE_POLICY_FRAME_COMPRESS_STEP_INTERVAL_US;
    compress_policy.activation_mask  = FUSE_POLICY_FRAME_COMPRESS_ACTIVATION_MASK;
    compress_policy.event_subscribe  = FUSE_POLICY_FRAME_COMPRESS_EVENT_SUBSCRIBE;

    printf("=== FUSE camera-filter-compress demo ===\n");
    printf("  frame_filter   : %s (%u bytes)\n", argv[1], filter_size);
    printf("    capabilities=0x%x  pages=%u  quota=%u us  events=0x%08x\n",
           filter_policy.capabilities, filter_policy.memory_pages_max,
           filter_policy.cpu_quota_us, filter_policy.event_subscribe);
    printf("  frame_compress : %s (%u bytes)\n", argv[2], compress_size);
    printf("    capabilities=0x%x  pages=%u  quota=%u us  events=0x%08x\n",
           compress_policy.capabilities, compress_policy.memory_pages_max,
           compress_policy.cpu_quota_us, compress_policy.event_subscribe);
    printf("\n");

    /* --- Initialise FUSE --- */
    fuse_hal_t hal;
    memset(&hal, 0, sizeof(hal));
    hal.timer.get_timestamp = hal_timer;
    hal.camera.last_frame   = hal_camera;
    hal.quota_arm           = hal_quota_arm;
    hal.quota_cancel        = hal_quota_cancel;

    fuse_stat_t rc = fuse_init(g_module_mem, sizeof(g_module_mem),
                               g_log_mem,    sizeof(g_log_mem),
                               &hal);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_init failed: %s\n", fuse_stat_name(rc));
        free(filter_buf);
        free(compress_buf);
        return 1;
    }

    /* --- Load and start frame_filter --- */
    fuse_module_id_t filter_id = FUSE_INVALID_MODULE_ID;
    rc = fuse_module_load(filter_buf, filter_size, &filter_policy, &filter_id);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_load (frame_filter) failed: %s\n",
                fuse_stat_name(rc));
        fuse_stop();
        free(filter_buf);
        free(compress_buf);
        return 1;
    }
    rc = fuse_module_start(filter_id);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_start (frame_filter) failed: %s\n",
                fuse_stat_name(rc));
        fuse_module_unload(filter_id);
        fuse_stop();
        free(filter_buf);
        free(compress_buf);
        return 1;
    }

    /* --- Load and start frame_compress --- */
    fuse_module_id_t compress_id = FUSE_INVALID_MODULE_ID;
    rc = fuse_module_load(compress_buf, compress_size, &compress_policy, &compress_id);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_load (frame_compress) failed: %s\n",
                fuse_stat_name(rc));
        fuse_module_unload(filter_id);
        fuse_stop();
        free(filter_buf);
        free(compress_buf);
        return 1;
    }
    rc = fuse_module_start(compress_id);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_start (frame_compress) failed: %s\n",
                fuse_stat_name(rc));
        fuse_module_unload(compress_id);
        fuse_module_unload(filter_id);
        fuse_stop();
        free(filter_buf);
        free(compress_buf);
        return 1;
    }

    printf("  filter   module id: %u\n", filter_id);
    printf("  compress module id: %u\n", compress_id);
    printf("  simulating %d frames (even=varied/high-MAD, odd=uniform/MAD=0)\n\n",
           NUM_FRAMES);

    assert(filter_id < 32u);
    assert(compress_id < 32u);
    uint32_t filter_bit   = (uint32_t)1u << filter_id;
    uint32_t compress_bit = (uint32_t)1u << compress_id;

    int frames_posted  = 0;
    int compress_count = 0;
    int reject_count   = 0;
    int abort_loop     = 0;

    int frame_num;
    for (frame_num = 0; frame_num < NUM_FRAMES && !abort_loop; ++frame_num) {
        int varied = ((frame_num % 2) == 0);
        init_sim_frame(varied);
        ++frames_posted;

        printf("[frame %2d] posting CAMERA_FRAME_READY (%s)\n",
               frame_num, varied ? "varied/high-MAD" : "uniform/MAD=0");
        fflush(stdout);

        rc = fuse_post_event(FUSE_EVENT_CAMERA_FRAME_READY);
        if (rc != FUSE_SUCCESS) {
            fprintf(stderr, "  fuse_post_event failed: %s\n", fuse_stat_name(rc));
            abort_loop = 1;
            break;
        }

        /* --- Phase 1: wait for frame_filter to run --- */
        int filter_ran   = 0;
        int compress_ran = 0;
        int t;
        for (t = 0; t < MAX_TICKS_PER_FRAME; ++t) {
            uint32_t ran = fuse_tick();

            if (ran & filter_bit)   filter_ran   = 1;
            if (ran & compress_bit) compress_ran = 1;

            if (filter_ran) break;
            usleep(1000);  /* 1 ms poll interval */
        }

        /* Check for terminal states before proceeding. */
        if (module_is_terminal(filter_id)) {
            fprintf(stderr, "  frame_filter entered terminal state — aborting\n");
            abort_loop = 1;
            break;
        }
        if (module_is_terminal(compress_id)) {
            fprintf(stderr, "  frame_compress entered terminal state — aborting\n");
            abort_loop = 1;
            break;
        }

        if (!filter_ran) {
            fprintf(stderr, "  timeout waiting for frame_filter\n");
            /* Count as a rejection for summary purposes. */
            ++reject_count;
            printf("          -> filter timeout\n");
            usleep(50000);
            continue;
        }

        /* --- Phase 2: if filter accepted, wait for frame_compress --- */
        if (!compress_ran) {
            for (t = 0; t < 10; ++t) {
                uint32_t ran = fuse_tick();
                if (ran & compress_bit) { compress_ran = 1; break; }
                usleep(1000);
            }

            /* Check terminal state of compress module after ticking. */
            if (module_is_terminal(compress_id)) {
                fprintf(stderr, "  frame_compress entered terminal state — aborting\n");
                abort_loop = 1;
                break;
            }
        }

        if (compress_ran) {
            ++compress_count;
            printf("          -> compressed\n");
        } else {
            ++reject_count;
            printf("          -> rejected by filter\n");
        }

        fflush(stdout);
        usleep(50000);  /* 50 ms between frames */
    }

    /* --- Teardown --- */
    /* Unload modules before stopping the runtime to avoid WASM re-entry
     * after a stop condition (relevant if modules export module_deinit). */
    fuse_module_unload(compress_id);
    fuse_module_unload(filter_id);
    fuse_stop();

    printf("\n=== Summary: frames=%d accepted+compressed=%d rejected=%d ===\n",
           frames_posted, compress_count, reject_count);

    free(filter_buf);
    free(compress_buf);
    return 0;
}
