/*
 * main.c — Camera compression demo host application
 *
 * Loads the camera_compress WASM/AOT module under FUSE, then drives execution
 * via fuse_tick() polled every 100 ms.  The module policy sets a 10 s step
 * interval, so one step fires roughly every 10 s for NUM_STEPS total steps.
 * Each step is limited to 1 ms of wall-clock CPU time via a SIGALRM quota.
 *
 * Usage (two modes):
 *
 *   Static  mode (compiled with -DFUSE_APP_CONFIG=app_config.json):
 *     camera_compress_host <module.aot>
 *       Policy is read from FUSE_POLICY_CAMERA_COMPRESS_* macros baked in at
 *       compile time via fuse_app_config.h.
 *
 *   Dynamic mode (policy delivered at runtime):
 *     camera_compress_host <module.aot> <policy.bin>
 *       policy.bin must be a 24-byte little-endian fuse_policy_t binary as
 *       produced by tools/policy_to_bin.py or tools/gen_app_config.py.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "fuse.h"
#include "platform/platform.h"

/* ---------------------------------------------------------------------------
 * Optional compile-time app config (generated by tools/gen_app_config.py).
 * Present only when CMake is invoked with -DFUSE_APP_CONFIG=app_config.json.
 * --------------------------------------------------------------------------- */
#if defined(__has_include) && __has_include("fuse_app_config.h")
#  include "fuse_app_config.h"
#endif

/* ---------------------------------------------------------------------------
 * Static FUSE memory pools (no dynamic allocation for FUSE itself).
 * Sizes come from app_config.h macros when available; fall back to fixed
 * compile-time constants that match the demo's default app_config.json.
 * --------------------------------------------------------------------------- */
#ifdef FUSE_APP_WAMR_POOL_BYTES
static uint8_t g_module_mem[FUSE_APP_WAMR_POOL_BYTES];
static uint8_t g_log_mem[FUSE_APP_LOG_POOL_BYTES];
#else
static uint8_t g_module_mem[8u * 1024u * 1024u];  /* 8 MB WAMR pool   */
static uint8_t g_log_mem[64u * 1024u];             /* 64 KB log ring   */
#endif

/* ---------------------------------------------------------------------------
 * Simulated camera
 * --------------------------------------------------------------------------- */
#define SIM_FRAME_SIZE (256u * 1024u)   /* 256 KB synthetic frame */

static uint8_t g_sim_frame[SIM_FRAME_SIZE];
static int     g_frame_ready = 0;

static void init_sim_frame(void)
{
    /* Gradient pattern — friendly to RLE on runs of same value */
    for (unsigned int i = 0u; i < SIM_FRAME_SIZE; ++i) {
        g_sim_frame[i] = (uint8_t)(i / 256u);  /* 256-byte constant runs */
    }
    g_frame_ready = 1;
}

/* ---------------------------------------------------------------------------
 * HAL callbacks
 * --------------------------------------------------------------------------- */

static uint64_t hal_camera(void *buf, uint32_t max_len)
{
    /* buf has already been validated by fuse_native_camera_last_frame()
     * via wasm_runtime_validate_native_addr() before this callback is
     * invoked (see core/camera/fuse_hal_camera.c).  A NULL check here is a
     * defence-in-depth guard only. */
    if (buf == NULL || max_len == 0u) {
        return 0u;
    }
    if (!g_frame_ready) {
        init_sim_frame();
    }
    uint32_t copy_len = (SIM_FRAME_SIZE < max_len) ? SIM_FRAME_SIZE : max_len;
    memcpy(buf, g_sim_frame, copy_len);
    return (uint64_t)copy_len;
}

/* ---------------------------------------------------------------------------
 * Helpers
 * --------------------------------------------------------------------------- */

static uint8_t *read_file(const char *path, uint32_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "error: cannot open '%s'\n", path);
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    rewind(f);
    if (sz <= 0) {
        fprintf(stderr, "error: empty or unreadable file '%s'\n", path);
        fclose(f);
        return NULL;
    }
    if ((unsigned long)sz > (unsigned long)UINT32_MAX) {
        fprintf(stderr, "error: file '%s' exceeds 4 GB\n", path);
        fclose(f);
        return NULL;
    }
    uint8_t *buf = (uint8_t *)malloc((size_t)sz);
    if (!buf) {
        fprintf(stderr, "error: malloc failed for %ld bytes\n", sz);
        fclose(f);
        return NULL;
    }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        fprintf(stderr, "error: short read on '%s'\n", path);
        free(buf);
        fclose(f);
        return NULL;
    }
    fclose(f);
    *out_size = (uint32_t)sz;
    return buf;
}

static const char *fuse_stat_name(fuse_stat_t s)
{
    switch (s) {
        case FUSE_SUCCESS:               return "FUSE_SUCCESS";
        case FUSE_ERR_QUOTA_EXCEEDED:    return "FUSE_ERR_QUOTA_EXCEEDED";
        case FUSE_ERR_MODULE_TRAP:       return "FUSE_ERR_MODULE_TRAP";
        case FUSE_ERR_INVALID_ARG:       return "FUSE_ERR_INVALID_ARG";
        case FUSE_ERR_NOT_INITIALIZED:   return "FUSE_ERR_NOT_INITIALIZED";
        case FUSE_ERR_MODULE_NOT_FOUND:  return "FUSE_ERR_MODULE_NOT_FOUND";
        default:                          return "FUSE_ERR_OTHER";
    }
}

/* ---------------------------------------------------------------------------
 * main
 * --------------------------------------------------------------------------- */

#define NUM_STEPS   5

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr,
                "usage: %s <module.aot> [policy.bin]\n"
                "\n"
                "  Static  mode (no policy.bin): uses FUSE_POLICY_CAMERA_COMPRESS_*\n"
                "    macros compiled in from fuse_app_config.h.  Rebuild with\n"
                "    -DFUSE_APP_CONFIG=<path/to/app_config.json> to enable.\n"
                "\n"
                "  Dynamic mode (policy.bin supplied): reads the 24-byte little-endian\n"
                "    fuse_policy_t binary produced by tools/policy_to_bin.py.\n",
                argv[0]);
        return 1;
    }

    /* --- Initialise platform (signal handlers, timer resources) --- */
    fuse_platform_init();

    /* --- Load AOT binary --- */
    uint32_t aot_size = 0u;
    uint8_t *aot_buf  = read_file(argv[1], &aot_size);
    if (!aot_buf) return 1;

    /* --- Resolve policy (dynamic or static) --- */
    fuse_policy_t  policy;
    uint8_t       *policy_buf  = NULL; /* heap buffer; freed after load */
    const char    *policy_mode = NULL;

    if (argc >= 3) {
        /* Dynamic mode: deserialise the 24-byte binary supplied on the command line. */
        uint32_t policy_size = 0u;
        policy_buf = read_file(argv[2], &policy_size);
        if (!policy_buf) {
            free(aot_buf);
            return 1;
        }

        fuse_stat_t prc = fuse_policy_from_bin(policy_buf, policy_size, &policy);
        if (prc != FUSE_SUCCESS) {
            fprintf(stderr,
                    "error: fuse_policy_from_bin failed (%s) — "
                    "policy.bin must be exactly %zu bytes\n",
                    fuse_stat_name(prc), sizeof(fuse_policy_t));
            free(policy_buf);
            free(aot_buf);
            return 1;
        }
        policy_mode = "dynamic (policy.bin)";

#ifdef FUSE_POLICY_CAMERA_COMPRESS_CAPABILITIES
    } else {
        /* Static mode: macros from fuse_app_config.h are available. */
        policy.capabilities     = FUSE_POLICY_CAMERA_COMPRESS_CAPABILITIES;
        policy.memory_pages_max = FUSE_POLICY_CAMERA_COMPRESS_MEMORY_PAGES_MAX;
        policy.stack_size       = FUSE_POLICY_CAMERA_COMPRESS_STACK_SIZE;
        policy.heap_size        = FUSE_POLICY_CAMERA_COMPRESS_HEAP_SIZE;
        policy.cpu_quota_us     = FUSE_POLICY_CAMERA_COMPRESS_CPU_QUOTA_US;
        policy.step_interval_us = FUSE_POLICY_CAMERA_COMPRESS_STEP_INTERVAL_US;
        policy_mode = "static (fuse_app_config.h)";
#else
    } else {
        /* No policy.bin argument and no compiled-in macros — cannot proceed. */
        fprintf(stderr,
                "error: no policy.bin argument and fuse_app_config.h macros are not\n"
                "  available.  Either pass a policy.bin file, or rebuild with:\n"
                "    cmake -DFUSE_APP_CONFIG=<path/to/app_config.json> ...\n");
        free(aot_buf);
        return 1;
#endif
    }

    printf("=== FUSE camera-compress demo ===\n");
    printf("  module : %s (%u bytes)\n", argv[1], aot_size);
    printf("  policy : %s\n", policy_mode);
    printf("           capabilities=0x%x  pages=%u  quota=%u us\n",
           policy.capabilities, policy.memory_pages_max,
           policy.cpu_quota_us);

    /* --- Initialise FUSE --- */
    fuse_hal_t hal;
    memset(&hal, 0, sizeof(hal));
    hal.timer.get_timestamp = fuse_platform_get_timestamp_us;
    hal.camera.last_frame   = hal_camera;
    hal.quota_arm           = fuse_platform_quota_arm;
    hal.quota_cancel        = fuse_platform_quota_cancel;

    fuse_stat_t rc = fuse_init(g_module_mem, sizeof(g_module_mem),
                               g_log_mem,    sizeof(g_log_mem),
                               &hal);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_init failed: %s\n", fuse_stat_name(rc));
        free(aot_buf);
        free(policy_buf);
        return 1;
    }

    /* --- Load and start module --- */
    fuse_module_id_t mid = FUSE_INVALID_MODULE_ID;
    rc = fuse_module_load(aot_buf, aot_size, &policy, &mid);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_load failed: %s\n", fuse_stat_name(rc));
        fuse_stop();
        free(aot_buf);
        free(policy_buf);
        return 1;
    }

    rc = fuse_module_start(mid);
    if (rc != FUSE_SUCCESS) {
        fprintf(stderr, "fuse_module_start failed: %s\n", fuse_stat_name(rc));
        fuse_module_unload(mid);
        fuse_stop();
        free(aot_buf);
        free(policy_buf);
        return 1;
    }

    printf("  module id: %u  — running %d steps\n", mid, NUM_STEPS);
    printf("  polling with fuse_tick() every 100 ms (step interval: 10 s)\n\n");

    /* --- fuse_tick() poll loop --- */
    int ok_count    = 0;
    int quota_count = 0;
    int trap_count  = 0;

    while (ok_count < NUM_STEPS) {
        fuse_platform_sleep_us(100000u);  /* 100 ms poll interval */

        uint32_t ran = fuse_tick();

        if (ran & ((uint32_t)1u << mid)) {
            ++ok_count;
            printf("[step %d/%d] completed\n", ok_count, NUM_STEPS);
            fflush(stdout);
        }

        /* Check if module entered a terminal state */
        fuse_module_state_t st;
        fuse_module_stat(mid, &st);
        if (st == FUSE_MODULE_STATE_QUOTA_EXCEEDED) {
            ++quota_count;
            printf("  module quota exceeded — stopping.\n");
            break;
        }
        if (st == FUSE_MODULE_STATE_TRAPPED) {
            ++trap_count;
            printf("  module trapped — stopping.\n");
            break;
        }
    }

    /* --- Teardown --- */
    fuse_module_unload(mid);
    fuse_stop();

    printf("\n=== Summary: ok=%d quota_exceeded=%d trap/other=%d ===\n",
           ok_count, quota_count, trap_count);

    free(aot_buf);
    free(policy_buf);
    return 0;
}
